### PR TITLE
added support for tuya based bulbs

### PR DESCRIPTION
**Pull request by samuscherer**
I looked at the communication between the bulb and the Tuya Smart Life app and I was able to understand some of the values that were being transmitted. There are two modes (colour mode and white mode). If your're in colour mode the values for brightness and colour temperature are being ignored. To change them in colour mode you have to calculate the new rgb values (e.g. convert it to hsv and add the brightness to V). There are still a couple of bytes left which don't make any sense to me - changing them didn't change the colour or the temperature or anything else. Maybe someone can take a look at those...

### CODE REVIEW

**Comment by Exilit** [comment]
I was working on this for some time also. Did you see the [DeviceSchema](https://github.com/clach04/python-tuya/wiki/DeviceSchemas) for RGB light bulbs? It provides a lot of information. In my opinio the value for entry "5" is encoded like this: rrggbb 00 hhssvv.
I assume the "00" in the middle acts like a delimiter or something like that.

**Comment by samuscherer** [comment]
Yeah, I thought the exact same thing as you but I wasn't able to reproduce a consistent behaviour of the bulb when I changed the first 3 bytes and the last 3 bytes. I might give it another shot this evening, I'm currently working on a tuya integration for Home Assistant.

**Comment by cycorld** [comment]
Thank you for your code. But I have problems.
I wrote code below.
```
...
d = pytuya.OutletDevice(DEVICE_ID, IP_ADDRESS, LOCAL_KEY)
data = d.set_white(25, 250)
...
```
The error messages is...
```
Traceback (most recent call last):
  File "go.py", line 9, in <module>
    data = d.set_white(25, 250)  # This requires a valid key
  File "/Users/charles/Documents/workspace/Project/smartbulb/python-tuya/pytuya/__init__.py", line 319, in set_white
    payload = self.generate_payload(SET, {'2':'white', '3':brightness, '4':colourtemp})
  File "/Users/charles/Documents/workspace/Project/smartbulb/python-tuya/pytuya/__init__.py", line 230, in generate_payload
    assert len(postfix_payload) <= 0xff
AssertionError
```
Could you show me your test code?

**Comment by clach04** [comment]
@samuscherer Thanks for sharing what you have so far, looking good!

I few recommendations/requests. It would be a good idea to separate the setup.py change away from the Bulb support (e.g. there maybe discussion on pycrypto and/or pycryptodome).

I recommend adding a new class for RBG bulbs, rather than adding this to the outlet class.

For API to set_white(), those parameters are bytes, I think supporting integer parameters will be an easier api for end users - I wonder if that's the issue that @cycorld experienced? As @cycorld suggested, adding new tests to the unit tests will be needed.

**Comment by samuscherer** [comment]
Hey @cycorld - it's true, those two parameters of set_white() are bytes. I actually can't remember why I decided not to use integers. I'll fix this.

@clach04 Thank you for your comments! You're more than correct with all you said - I'll try to implement everything today/tomorrow.

**Comment by samuscherer** [comment]
Due to the changes and to keep the setup.py separate, I'll create a new pull request.

**Pull request closed without merging**
