### PR TITLE
Refactored XenonDevice.generate_payload()

### PR DESCRIPTION
**Pull request by Exilit**
The generate_payload() method is now more generic and is also used by
OutletDevice.set_timer(). This removes a lot of duplicate code.

### CODE REVIEW

**Comment by Exilit** [comment]
I reworked my refactoring a little. This commit now uses a dict as argument for `XenonDevice.generate_payload()` but I left the constants in place.

**Comment by clach04** [comment]
Apologies for not responding sooner. I've not had chance to run this yet. From quick scan, code looks good.

Things that stick out:

  * I like the use of dicts
  * commit states "and is also used by OutletDevice.set_timer()" - pre this change this was also the case. This should be removed from commit message
  * removes OFF and ON in dict, `OFF` no longer used in preference for `SET` (great idea 👍 ). `ON` still used in one place. Please continue removal of ON and OFF constant usage along with definitions and mention in commit.

**Comment by Exilit** [comment]
Thanks for the review. I will clean up the commit. I obviously forgot to change the commit message after syncing back with your repo.

Do you think amending and rebasing would break the pull request?

**Comment by clach04** [comment]
I've done a rebase and force push on an open PR and it did work (was a while ago). Worst scenario, it doesn't work and open a new PR.

**Comment by Exilit** [comment]
Okay, I already rewrote the message and removed the ON and OFF constants but didn't push my commits. I will force push my changes next week.

**Comment by Exilit** [comment]
You have been right. Github seems to be able to resolve rebased branches in pull requests.

**Comment by clach04** [comment]
Thank you! Sorry for the delay in getting to this.

**Comment by Exilit** [comment]
No problem, thanks for merging.

**Pull request merged**
